base:
  domain: api.order-book.network
  base_path: /api/v1
http:
  addr: 0.0.0.0:8007
  cors_allow_origins:
  - '*'
  proxy_forwarded_header: ""
  log_all_requests: false
logging:
  format: text
  level: debug
